---
output: github_document
authors: Amandine Vidal-Hosteng, Christophe Thébaud, Rampal Etienne, Robin Aguilée
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Colonization IBM"
```

# Archipelago with sea-level fluctuations IBM

--

## Contents

  - [:file_folder: Simulation](R)
    - [Cfunctions.C](C) - Gathers the functions constituting the model and written in C.
    - [Rfunctions.r](R) - Gathers the functions called by the main file and written in R (except the plotresults.r and plotequilibrium.r which are in separate files; see below);
    - [build_phylo.r](R)
    - [build_phylo_functions.r](R)
    - [parameters.r](R) - Gathers the parameters values (see below).
    - [plotresults.r](R) - Computes and plot the outputs characterizing the state and evolution of the population 
    - [plottopo.r](R) - Computes and plot the outputs characterizing the landscape parameters
    - [simulation.r](R) - Is the main program file. This is the one to run.
    - [stat_past.r](R)
    - [stat_phylo.r](R)

## Parameters and outputs

'islarch': if set to 0, it corresponds to an archipelago. If set to 2, it corresponds to the null model 'island archipelago-equivalent' described in the article. The code allows a third option, islarch set to 1, not described in the article, which corresponds to a single island of the size of the archipelago assuming that this single island is circular. In this case, the migration angle allowing to reach the archipelago and the equivalent single island is not the same (whereas it is the same when islarch is set to 2; see details in Appendix 1 of the article). 
'ti' in the code corresponds to 'tstart' in the article (see Appendix 1 of the article). The parameter 'tinter' in the article is not explicitly given in the parameter file but it follows from the value of 'tstart'
'tl' in the code corresponds to 'tlife' in the article

### Licenses

**Code :** See the [DESCRIPTION](DESCRIPTION) file

